#ifndef LUFTFUGL_CONFIG_H
#define LUFTFUGL_CONFIG_H

#include <stdbool.h>
#include <stdint.h>

#define FW_VERSION "1.0.0"

#define PIN_AIN1 2
#define PIN_AIN2 3
#define PIN_PWMA 14
#define PIN_STBY 15
#define PIN_SENSE 26
#define ADC_CHANNEL 0
#define PIN_UART_TX 8
#define PIN_UART_RX 9
#define PIN_LED_POWER 0
#define PIN_LED_DATA 18
#define PIN_BUZZER_BIN1 6
#define PIN_BUZZER_BIN2 7
#define PIN_BUZZER_PWMB 16
#define BUZZER_STATION_5_PLAYS 3u
#define PIN_I2C_SDA 4
#define PIN_I2C_SCL 5
#define PIN_CO2_LIMIT_AB 10
#define I2C_BAUD 100000u
#define SCD41_ADDRESS 0x62u
#define CO2_LIVING_LEVEL1_MAX_PPM 799u
#define CO2_LIVING_LEVEL2_MAX_PPM 999u
#define CO2_LIVING_LEVEL3_MAX_PPM 1499u
#define CO2_LIVING_LEVEL4_MAX_PPM 2000u
#define CO2_SLEEPING_LEVEL1_MAX_PPM 999u
#define CO2_SLEEPING_LEVEL2_MAX_PPM 1499u
#define CO2_SLEEPING_LEVEL3_MAX_PPM 1999u
#define CO2_SLEEPING_LEVEL4_MAX_PPM 2500u
#define CO2_SIM_MIN_PPM 200u
#define CO2_SIM_MAX_PPM 6000u
#define CO2_SIM_MAPPING_PERIOD_MS 5000u
#define INA219_ADDRESS 0x40u
#define LED_COUNT 1
#define LED_RGBW 1
#define LED_POWER_STARTUP_US 300u
#define LED_STATION_BRIGHTNESS_PERCENT 3u
#define LED_HAZARD_BRIGHTNESS_PERCENT 30u

#define LED_STATION5_R 192
#define LED_STATION5_G 4
#define LED_STATION5_B 8
#define LED_STATION4_R 160
#define LED_STATION4_G 24
#define LED_STATION4_B 48
#define LED_STATION3_R 160
#define LED_STATION3_G 48
#define LED_STATION3_B 0
#define LED_STATION2_R 96
#define LED_STATION2_G 144
#define LED_STATION2_B 8
#define LED_STATION1_R 0
#define LED_STATION1_G 224
#define LED_STATION1_B 24
#define LED_HAZARD_PERIOD_MS 1000u
#define LED_HAZARD_PULSE_MS 150u
#define LED_HAZARD_GAP_MS 150u
#define LED_BATTERY_R 255u
#define LED_BATTERY_G 48u
#define LED_BATTERY_B 0u
#define LED_BATTERY_BRIGHTNESS_PERCENT 100u
#define BATTERY_WARN_MV 3600u
#define BATTERY_CRITICAL_MV 3300u
#define BATTERY_WARNING_MIN_MV 1400u
#define BATTERY_WARNING_MAX_MV 5400u
#define BATTERY_CRITICAL_MIN_MV 2200u
#define BATTERY_CRITICAL_MAX_MV 5900u
#define BATTERY_ALERT_FREQUENCY_HZ 3500u
#define BATTERY_ALERT_FREQUENCY_MIN_HZ 100u
#define BATTERY_ALERT_FREQUENCY_MAX_HZ 10000u
#define BATTERY_CHIRP_INTERVAL_DEFAULT_S 30u
#define BATTERY_CHIRP_REPEAT_DEFAULT 2u
#define BATTERY_CHIRP_PAUSE_DEFAULT_S 5u
#define BATTERY_CHIRP_DURATION_DEFAULT_S 3u
#define BATTERY_CHIRP_INTERVAL_MIN_S 1u
#define BATTERY_CHIRP_INTERVAL_MAX_S 3600u
#define BATTERY_CHIRP_REPEAT_MIN 1u
#define BATTERY_CHIRP_REPEAT_MAX 10u
#define BATTERY_CHIRP_PAUSE_MIN_S 1u
#define BATTERY_CHIRP_PAUSE_MAX_S 10u
#define BATTERY_CHIRP_DURATION_MIN_S 1u
#define BATTERY_CHIRP_DURATION_MAX_S 5u
#define BATTERY_SIM_RANGE_MIN_MV 1000u
#define BATTERY_SIM_RANGE_MAX_MV 6000u
#define BATTERY_SIM_DEFAULT_MIN_MV 3900u
#define BATTERY_SIM_DEFAULT_MAX_MV 4500u

#define PWM_WRAP 255
#define PWM_CLKDIV 97.6875f

#define DUTY_NORMAL 50
#define DUTY_APPROACH 25
#define DUTY_CREEP 25
#define DUTY_MIN 25

#define POS_1_ADC 200  /*  17.6 deg */
#define POS_2_ADC 611  /*  53.7 deg */
#define POS_3_ADC 1022 /*  89.8 deg */
#define POS_4_ADC 1433 /* 126.0 deg */
#define POS_5_ADC 1844 /* measured upper-station ADC from trace */
#define POS_WINDOW 20
#define LED_STATION_WINDOW_COUNTS 20
#define ARRIVAL_WINDOW_COUNTS 15
#define APPROACH_COUNTS 300
#define LOW_ENDSTOP_ADC 100
#define HIGH_ENDSTOP_ADC 2000

#define TICK_HZ 1000
#define TICK_PERIOD_US 1000u
#define FILTER_DEPTH 5
#define DEBOUNCE_MS 12
#define BRAKE_HOLD_MS 100
#define TIMEOUT_STEP_MS 30000u
#define TIMEOUT_HOME_MS 6000u
#define JOG_TIMEOUT_MS 3000u

#define CONSOLE_LINE_MAX 32
#define EVENT_QUEUE_DEPTH 8
#define UART_BAUD 115200

/* INA219 and battery model. Zero marks a bench value that has not yet been
 * measured; diagnostics say "not measured" and the associated detector stays
 * disabled. */
#define BATTERY_CAPACITY_MAH 2500u
#define SLEEP_CURRENT_UA 0u
#define NO_LOAD_CURRENT_MA 0u
#define STALL_CURRENT_MA 0u
#define STALL_DETECT_MS 0u
#define SHORT_CIRCUIT_MA 0u
#define RPACK_FRESH_MOHM 0u
#define INRUSH_SAMPLE_MS 20u
#define EVENT_LOG_DEPTH 16u
#define RUN_CURRENT_DEPTH 16u
#define RPACK_MIN_SAMPLES 10u
#define INA219_SHUNT_MOHM 100u
#define INA219_CURRENT_LSB_UA 100u
#define INA219_BUS_LSB_MV 4u
#define INA219_SHUNT_LSB_UV 10u
#define INA219_POWER_LSB_UW (20u * INA219_CURRENT_LSB_UA)
#define INA219_NORMAL_CONFIG 0x119bu
#define INA219_POWER_DOWN_CONFIG 0x1198u
#define INA219_INRUSH_CONFIG 0x1003u
#define INA219_SAMPLE_PERIOD_MS 1000u

#define ADC_MAX_VALUE 4095u
#ifdef LUFTFUGL_MONITOR
#define DEBUG_INTERLOCK_TIMEOUT_MS 120000u
#define DEBUG_STREAM_MIN_HZ 1u
#define DEBUG_STREAM_DEFAULT_HZ 10u
#define DEBUG_STREAM_MAX_HZ 50u
#define DEBUG_ADC_MONITOR_PERIOD_MS 100u
#define DEBUG_PULSE_DEFAULT_MS 150u
#define DEBUG_PULSE_MIN_MS 10u
#define DEBUG_PULSE_MAX_MS 2000u
#define DEBUG_FINDMIN_DUTY_OFFSET 20u
#define DEBUG_FINDMIN_DUTY_STEP 5u
#define DEBUG_FINDMIN_PULSE_MS 150u
#define DEBUG_FINDMIN_DUTY_MAX 120u
#define DEBUG_FINDMIN_MARGIN_PERCENT 10u
#define DEBUG_CAL_SAMPLE_MS 500u
#define DEBUG_CAL_MIN_SEPARATION 200u
#define DEBUG_CAL_ROUND_MS 100u
#define DEBUG_CFG_TIMEOUT_MIN_MS 100u
#define DEBUG_OVERSHOOT_DUTY_HIGH 80u
#define DEBUG_OVERSHOOT_DUTY_MID 60u
#define DEBUG_OVERSHOOT_DUTY_LOW 40u
#define DEBUG_OVERSHOOT_TEST_COUNT 6u
#define DEBUG_NOMINAL_P3 POS_3_ADC
#define DEBUG_HISTORY_DEPTH 64u
#define DEBUG_MOTION_TRACE_PERIOD_MS 50u
#define DEBUG_OUT_BUFFER 4096u
#define DEBUG_SELFTEST_ADC_SAMPLES 10u
#define DEBUG_SELFTEST_SAMPLE_PERIOD_MS 1u
#define DEBUG_SELFTEST_WINDOW_MS 1000u
#define DEBUG_SELFTEST_TICK_TOLERANCE 20u
#define DEBUG_PERCENT_SCALE 100u
#define DEBUG_BENCH_PIN_PERIOD_MS 200u
#define DEBUG_GPIO_WALK_STEP_MS 1000u
#define DEBUG_TICK_HEALTH_WINDOW_MS 2000u
#define DEBUG_SIM_DEFAULT_ADC POS_1_ADC
#define DEBUG_SIM_MIN_POSITION_MS DEBOUNCE_MS
#define DEBUG_SIM_SWEEP_SETTLE_MS (FILTER_DEPTH + DEBOUNCE_MS)
#define CAL_SIM_TESTS 50u
#define CAL_SIM_SETTLE_MS 20u
#define CAL_MOTOR_SETTLE_MS 50u
#define DEBUG_MENU_BUFFER_SIZE 512u
#define DEBUG_HEADER_BUFFER_SIZE 256u
#define DEBUG_PWM_DIV_MASK 0x0fffu
#define DEBUG_PWM_FIXED_SCALE 16u
#define DEBUG_FREQ_TENTHS 10u
#define DEBUG_DECIMAL_4_SCALE 10000u
#define DEBUG_PWM_SPEC_HZ 5000u
#define DEBUG_PWM_TOLERANCE_PERCENT 1u
#define DEBUG_TICK_RATE_TOLERANCE_HZ 20u
#define DEBUG_GPIO_OP_ALL_LOW 0u
#define DEBUG_GPIO_OP_AIN1 1u
#define DEBUG_GPIO_OP_AIN2 2u
#define DEBUG_GPIO_OP_STBY 3u
#define DEBUG_SCREEN_REFRESH_MS 200u
#define DEBUG_SCREEN_UPTIME_MS 1000u
#define DEBUG_SCREEN_BOTTOM_ROW 53u
#define DEBUG_COMMAND_ROW 24u
#define DEBUG_EVENT_TOP_ROW 25u
#define DEBUG_PAGE6_COMMAND_ROW 30u
#define DEBUG_PAGE6_EVENT_TOP_ROW 31u
#define DEBUG_JOG_STEP_DEFAULT 100u
#define DEBUG_JOG_STEP_1 10u
#define DEBUG_JOG_STEP_2 25u
#define DEBUG_JOG_STEP_3 50u
#define DEBUG_JOG_STEP_4 100u
#define DEBUG_JOG_STEP_5 250u
#define DEBUG_JOG_STEP_6 500u
#endif

#define POS_UNKNOWN 0
#define POS_MIN 1
#define POS_MAX 5
#define POS_BETWEEN 6
typedef uint8_t position_t;

typedef enum { DIR_STOP = 0, DIR_FWD, DIR_REV } direction_t;
typedef enum {
  ST_BOOT = 0,
  ST_IDLE,
  ST_MOVING,
  ST_APPROACH,
  ST_HOMING,
  ST_FAULT,
#ifdef LUFTFUGL_DEBUG
  ST_DEBUG,
#endif
} sys_state_t;
typedef enum {
  REQ_NONE = 0,
  REQ_MOVE,
  REQ_STOP,
  REQ_HOME,
  REQ_JOG,
  REQ_SETPOS,
  REQ_RESET_POSITIONS
} request_kind_t;
typedef enum {
  MOVE_OK = 0,
  MOVE_ALREADY,
  MOVE_INVALID,
  MOVE_BUSY,
  MOVE_POS_UNKNOWN,
  MOVE_FAULT
} move_result_t;
typedef enum {
  JOG_OK = 0,
  JOG_INVALID,
  JOG_BUSY,
  JOG_ENDSTOP
} jog_result_t;
typedef enum {
  EV_PASS = 0,
  EV_ARRIVE,
  EV_HOMING,
  EV_TIMEOUT,
  EV_FAULT_HOME,
  EV_STOPPED_UNKNOWN,
  EV_JOG_COMPLETE
} event_kind_t;

#ifdef LUFTFUGL_MONITOR
typedef enum {
  DBG_OP_NONE = 0,
  DBG_OP_ENTER,
  DBG_OP_EXIT,
  DBG_OP_DRIVE,
  DBG_OP_BRAKE,
  DBG_OP_COAST,
  DBG_OP_STANDBY,
  DBG_OP_SIM_ENABLE,
  DBG_OP_SIM_SET,
  DBG_OP_GPIO_SET,
  DBG_OP_GOTO_ADC
} dbg_op_t;
typedef struct {
  dbg_op_t op;
  direction_t dir;
  uint8_t duty;
  uint16_t ms;
  bool flag;
  uint16_t adc;
} dbg_request_t;

typedef struct {
  uint8_t duty_normal, duty_approach, duty_creep, duty_min;
  uint16_t pos_1_adc, pos_2_adc, pos_3_adc, pos_4_adc, pos_5_adc;
  uint16_t pos_window, approach_counts;
  uint16_t debounce_ms, brake_hold_ms;
  uint16_t low_endstop_adc, high_endstop_adc;
} cfg_t;
extern volatile cfg_t cfg;
void cfg_reset(void);
#define CFG_DUTY_NORMAL (cfg.duty_normal)
#define CFG_DUTY_APPROACH (cfg.duty_approach)
#define CFG_DUTY_CREEP (cfg.duty_creep)
#define CFG_DUTY_MIN (cfg.duty_min)
#define CFG_POS_1_ADC (cfg.pos_1_adc)
#define CFG_POS_2_ADC (cfg.pos_2_adc)
#define CFG_POS_3_ADC (cfg.pos_3_adc)
#define CFG_POS_4_ADC (cfg.pos_4_adc)
#define CFG_POS_5_ADC (cfg.pos_5_adc)
#define CFG_POS_WINDOW (cfg.pos_window)
#define CFG_ARRIVAL_WINDOW ARRIVAL_WINDOW_COUNTS
#define CFG_APPROACH_COUNTS (cfg.approach_counts)
#define CFG_DEBOUNCE_MS (cfg.debounce_ms)
#define CFG_BRAKE_HOLD_MS (cfg.brake_hold_ms)
#define CFG_LOW_ENDSTOP_ADC (cfg.low_endstop_adc)
#define CFG_HIGH_ENDSTOP_ADC (cfg.high_endstop_adc)
#else
#define CFG_DUTY_NORMAL DUTY_NORMAL
#define CFG_DUTY_APPROACH DUTY_APPROACH
#define CFG_DUTY_CREEP DUTY_CREEP
#define CFG_DUTY_MIN DUTY_MIN
#define CFG_POS_1_ADC POS_1_ADC
#define CFG_POS_2_ADC POS_2_ADC
#define CFG_POS_3_ADC POS_3_ADC
#define CFG_POS_4_ADC POS_4_ADC
#define CFG_POS_5_ADC POS_5_ADC
#define CFG_POS_WINDOW POS_WINDOW
#define CFG_ARRIVAL_WINDOW ARRIVAL_WINDOW_COUNTS
#define CFG_APPROACH_COUNTS APPROACH_COUNTS
#define CFG_DEBOUNCE_MS DEBOUNCE_MS
#define CFG_BRAKE_HOLD_MS BRAKE_HOLD_MS
#define CFG_LOW_ENDSTOP_ADC LOW_ENDSTOP_ADC
#define CFG_HIGH_ENDSTOP_ADC HIGH_ENDSTOP_ADC
#endif

#endif
