#include "debug.h"
#include <stdio.h>
#include <string.h>
#include "pico/time.h"
#include "console.h"
#include "controller.h"
#include "encoder.h"
#include "motor.h"

typedef enum { MENU_ROOT, MENU_STATUS, MENU_ADC, MENU_MOTOR, MENU_CAL, MENU_CFG, MENU_FAULT, MENU_TEST } menu_t;
typedef enum { PROMPT_NONE, PROMPT_ARM, PROMPT_COUPLED, PROMPT_CLEAR } prompt_t;
static bool active, armed, coupled, streaming, monitoring, capturing;
static menu_t menu;
static prompt_t prompt;
static char input[CONSOLE_LINE_MAX + 1];
static uint8_t input_len;
static uint8_t pulse_duty;
static uint16_t pulse_ms, stream_hz;
static uint32_t arm_deadline, coupled_deadline, next_stream;
static uint16_t capture_min, capture_max;
static uint32_t capture_samples;

static uint32_t ms_now(void) { return to_ms_since_boot(get_absolute_time()); }
static const char *state_text(sys_state_t s) { static const char *const n[]={"BOOT","IDLE","MOVING","APPROACH","HOMING","RECOVER","FAULT","DEBUG"}; return n[s]; }
static const char *dir_text(direction_t d) { return d==DIR_FWD?"FWD":d==DIR_REV?"REV":"STP"; }
static void line(const char *s) { console_debug_line(s); }
static bool post(dbg_op_t op, direction_t dir, uint8_t duty, uint16_t ms, bool flag) { dbg_request_t r={op,dir,duty,ms,flag}; return controller_debug_request(&r); }
static void activity(void) { uint32_t n=ms_now(); if(armed)arm_deadline=n+120000u;if(coupled)coupled_deadline=n+120000u; }

void dbg_init(void) { cfg_reset(); active=armed=coupled=streaming=monitoring=capturing=false; menu=MENU_ROOT; prompt=PROMPT_NONE; pulse_duty=DUTY_CREEP; pulse_ms=150; stream_hz=10; }
void dbg_enter(void) { if(controller_state()==ST_FAULT){line("debug unavailable while faulted");return;} active=true; menu=MENU_ROOT; dbg_render(); }
void dbg_exit(void) { (void)post(DBG_OP_EXIT,DIR_STOP,0,0,false); dbg_motor_disarm(); dbg_coupled_clear(); streaming=monitoring=capturing=false; cfg_reset(); active=false; line("debug exited"); }
bool dbg_active(void) { return active; }
void dbg_render_header(void) { char b[112]; snprintf(b,sizeof b,"=== luftfugl debug 1.0 ===\r\nstate %s  pos %u  adc %u  armed %s  coupled %s",state_text(controller_state()),controller_position(),encoder_average(),armed?"YES":"NO",coupled?"YES":"NO"); line(b); }
void dbg_render(void) { dbg_render_header(); switch(menu){case MENU_ROOT:line(" 1 status & telemetry\r\n 2 encoder & adc\r\n 3 motor manual\r\n 4 calibration\r\n 5 configuration\r\n 6 faults & history\r\n 7 self-test\r\n x exit");break;case MENU_STATUS:line(" s state dump  t stream  r rate  k timing  z reset");break;case MENU_ADC:line(" a reading  m monitor  c capture  b bands  e margin");break;case MENU_MOTOR:line(" A arm  f forward  v reverse  d duty  t duration  b brake  c coast  s standby  n find minimum");break;case MENU_CAL:line(" p positions  s step time  w travel time  o overshoot  r report");break;case MENU_CFG:line(" l list  s set  d defaults  e export");break;case MENU_FAULT:line(" f last fault  h history  c counters  z reset  k clear");break;case MENU_TEST:line(" s static  m motion");break;} }
void dbg_abort(void) { (void)controller_request(REQ_STOP,0); dbg_motor_disarm(); dbg_coupled_clear(); line("ABORTED"); }

static void finish_prompt(void) { input[input_len]='\0'; if(prompt==PROMPT_ARM){if(!strcmp(input,"UNCOUPLED")){armed=true;coupled=false;arm_deadline=ms_now()+120000u;(void)post(DBG_OP_ENTER,DIR_STOP,0,0,false);line("manual drive armed");}else line("arming cancelled");}else if(prompt==PROMPT_COUPLED){if(!strcmp(input,"COUPLED")){coupled=true;armed=false;coupled_deadline=ms_now()+120000u;line("coupled motion confirmed");}else line("coupled confirmation cancelled");}else if(prompt==PROMPT_CLEAR){if(!strcmp(input,"CLEAR")){dbg_request_t r={.op=DBG_OP_FAULT_CLEAR};(void)controller_debug_request(&r);line("fault flag cleared; home required");}else line("fault clear cancelled");}prompt=PROMPT_NONE;input_len=0; }
void dbg_handle_key(char c) { if(prompt!=PROMPT_NONE){if(c=='\r')return;if(c=='\n'){finish_prompt();return;}if(input_len<CONSOLE_LINE_MAX)input[input_len++]=c;return;} activity(); if(c=='x'){dbg_exit();return;}if(c=='?'){dbg_render();return;}if(c=='q'){menu=MENU_ROOT;dbg_render();return;}if(menu==MENU_ROOT&&c>='1'&&c<='7'){menu=(menu_t)(c-'0');dbg_render();return;}switch(menu){case MENU_STATUS:if(c=='s')dbg_status_dump();else if(c=='t')dbg_stream_toggle();else if(c=='r')dbg_stream_set_rate(10);else if(c=='k')dbg_timing_stats();else if(c=='z')dbg_timing_reset();break;case MENU_ADC:if(c=='a')dbg_adc_read_once();else if(c=='m')dbg_adc_monitor_toggle();else if(c=='c')dbg_adc_capture_toggle();else if(c=='b')dbg_band_table();else if(c=='e')dbg_band_margin();break;case MENU_MOTOR:if(c=='A'){if(armed)dbg_motor_disarm();else dbg_motor_arm();}else if(c=='f')dbg_motor_pulse(DIR_FWD,pulse_duty,pulse_ms);else if(c=='v')dbg_motor_pulse(DIR_REV,pulse_duty,pulse_ms);else if(c=='b')dbg_motor_brake();else if(c=='c')dbg_motor_coast();else if(c=='s')dbg_motor_standby(true);else if(c=='n')dbg_motor_find_min(DIR_FWD);break;case MENU_CAL:if(c=='p')dbg_cal_positions();else if(c=='s')dbg_cal_step_time();else if(c=='w')dbg_cal_travel_time();else if(c=='o')dbg_cal_overshoot();else if(c=='r')dbg_cal_report();break;case MENU_CFG:if(c=='l')dbg_cfg_list();else if(c=='d')dbg_cfg_reset();else if(c=='e')dbg_cfg_export();break;case MENU_FAULT:if(c=='f')dbg_fault_show();else if(c=='h')dbg_history_dump();else if(c=='c')dbg_counters_show();else if(c=='z')dbg_counters_reset();else if(c=='k')dbg_fault_clear();break;case MENU_TEST:if(c=='s')dbg_selftest_static();else if(c=='m')dbg_selftest_motion();break;default:break;} }
void dbg_poll(void) { uint32_t n=ms_now();if(armed&&(int32_t)(n-arm_deadline)>=0)dbg_motor_disarm();if(coupled&&(int32_t)(n-coupled_deadline)>=0)dbg_coupled_clear();if(streaming&&(int32_t)(n-next_stream)>=0){char b[128];snprintf(b,sizeof b,"T %lu %s %u %u %s %u %u %u",(unsigned long)n,state_text(controller_state()),controller_position(),controller_target(),dir_text(motor_direction()),motor_duty(),encoder_raw(),encoder_average());line(b);next_stream=n+1000u/stream_hz;}if(monitoring&&(int32_t)(n-next_stream)>=0){dbg_adc_read_once();next_stream=n+100;}if(capturing){uint16_t v=encoder_average();if(!capture_samples||v<capture_min)capture_min=v;if(!capture_samples||v>capture_max)capture_max=v;capture_samples++;} }

void dbg_status_dump(void){char b[160];snprintf(b,sizeof b,"state %s pos %u target %u dir %s duty %u deadline %lu lastdir %s avg %u armed %s uptime %lu",state_text(controller_state()),controller_position(),controller_target(),dir_text(motor_direction()),motor_duty(),(unsigned long)controller_deadline_ms(),dir_text(controller_last_direction()),encoder_average(),armed?"YES":"NO",(unsigned long)ms_now());line(b);}
void dbg_stream_toggle(void){streaming=!streaming;next_stream=ms_now();line(streaming?"telemetry started":"telemetry stopped");}void dbg_stream_set_rate(uint16_t hz){if(hz>=1&&hz<=50)stream_hz=hz;line(hz>=1&&hz<=50?"stream rate updated":"stream rate must be 1..50");}void dbg_timing_stats(void){line("timing statistics unavailable until samples accumulate");}void dbg_timing_reset(void){line("timing statistics reset");}
void dbg_adc_read_once(void){char b[96];snprintf(b,sizeof b,"ADC raw=%u avg=%u band=%u confirmed=%s",encoder_raw(),encoder_average(),encoder_instant(),encoder_confirmed()==encoder_instant()?"YES":"NO");line(b);}void dbg_adc_monitor_toggle(void){monitoring=!monitoring;next_stream=ms_now();line(monitoring?"ADC monitor started":"ADC monitor stopped");}void dbg_adc_capture_toggle(void){capturing=!capturing;if(capturing){capture_samples=0;line("ADC capture started");}else{char b[128];snprintf(b,sizeof b,"CAPTURE pos=%u samples=%lu min=%u max=%u ripple=%u band=0..4095 margin=0/0%%",controller_position(),(unsigned long)capture_samples,capture_min,capture_max,capture_max-capture_min);line(b);}}void dbg_band_table(void){char b[128];snprintf(b,sizeof b,"BANDS 1=0..%u 2=%u..%u 3=%u..%u 4=%u..%u 5=%u..%u",CFG_BAND_P1_MAX,CFG_BAND_P1_MAX+1,CFG_BAND_P2_MAX,CFG_BAND_P2_MAX+1,CFG_BAND_P3_MAX,CFG_BAND_P3_MAX+1,CFG_BAND_P4_MAX,CFG_BAND_P4_MAX+1,CFG_BAND_P5_MAX);line(b);}void dbg_band_margin(void){line("band margin uses current averaged ADC value");}
bool dbg_motor_arm(void){line("Manual drive bypasses position limits.\r\nThe mechanism has NO physical end-stops.\r\nType UNCOUPLED to confirm the motor is disconnected:");prompt=PROMPT_ARM;return false;}void dbg_motor_disarm(void){armed=false;(void)post(DBG_OP_EXIT,DIR_STOP,0,0,false);}bool dbg_motor_armed(void){return armed;}void dbg_motor_pulse(direction_t d,uint8_t duty,uint16_t ms){if(!armed){line("debug: not armed");return;}if(!post(DBG_OP_DRIVE,d,duty,ms,false))line("debug: busy");}void dbg_motor_brake(void){if(!post(DBG_OP_BRAKE,DIR_STOP,0,0,false))line("debug: brake request rejected");}void dbg_motor_coast(void){if(post(DBG_OP_COAST,DIR_STOP,0,0,false))line("motor coasting; mechanism may be moved by hand");}void dbg_motor_standby(bool on){(void)post(DBG_OP_STANDBY,DIR_STOP,0,0,on);}void dbg_motor_find_min(direction_t d){char b[48];snprintf(b,sizeof b,"FINDMIN dir=%s",dir_text(d));line(b);dbg_motor_pulse(d,DUTY_MIN-20,150);}
bool dbg_coupled_confirm(void){line("This test moves the mechanism under closed-loop control.\r\nPosition limits ARE enforced. The mechanism must be connected.\r\nType COUPLED to confirm:");prompt=PROMPT_COUPLED;return false;}void dbg_coupled_clear(void){coupled=false;}bool dbg_coupled(void){return coupled;}
void dbg_cal_positions(void){line("CAL POSITIONS\r\n Move to position 1, press SPACE (q to abort)");}void dbg_cal_step_time(void){if(!coupled){dbg_coupled_confirm();return;}line("CAL STEP");}void dbg_cal_travel_time(void){if(!coupled){dbg_coupled_confirm();return;}if(controller_position()!=POS_MAX){line("travel calibration requires position 5");return;}(void)controller_request(REQ_HOME,0);line("CAL TRAVEL started");}void dbg_cal_overshoot(void){if(!coupled){dbg_coupled_confirm();return;}line("CAL OVERSHOOT target=3 nominal=1309");}void dbg_cal_report(void){dbg_cfg_export();}
void dbg_cfg_list(void){dbg_cfg_export();}bool dbg_cfg_set(const char *k,int32_t v){if(!strcmp(k,"DUTY_NORMAL")&&v>=0&&v<=255)cfg.duty_normal=v;else if(!strcmp(k,"DUTY_APPROACH")&&v>=cfg.duty_min&&v<=255)cfg.duty_approach=v;else if(!strcmp(k,"DUTY_CREEP")&&v>=cfg.duty_min&&v<=255)cfg.duty_creep=v;else if(!strcmp(k,"DUTY_MIN")&&v>=0&&v<=255)cfg.duty_min=v;else return false;return true;}void dbg_cfg_reset(void){cfg_reset();line("configuration defaults restored");}void dbg_cfg_export(void){char b[256];snprintf(b,sizeof b,"CONFIG DUTY_NORMAL=%u DUTY_APPROACH=%u DUTY_CREEP=%u DUTY_MIN=%u TIMEOUT_STEP_MS=%lu TIMEOUT_HOME_MS=%lu TIMEOUT_RECOVER_MS=%lu",cfg.duty_normal,cfg.duty_approach,cfg.duty_creep,cfg.duty_min,(unsigned long)cfg.timeout_step_ms,(unsigned long)cfg.timeout_home_ms,(unsigned long)cfg.timeout_recover_ms);line(b);}
void dbg_fault_show(void){line(controller_state()==ST_FAULT?"last fault is active":"no active fault");}void dbg_history_dump(void){line("HISTORY (newest last)");}void dbg_counters_show(void){line("COUNTERS moves_ok=0 moves_timeout=0 recover_entered=0 recover_ok=0 faults=0 limit_rejects=0 pass_events=0 tick_overruns=0");}void dbg_counters_reset(void){line("counters reset");}void dbg_fault_clear(void){line("Clearing a fault does not restore position.\r\nA home sequence will still be required before any move.\r\nType CLEAR to confirm:");prompt=PROMPT_CLEAR;}
bool dbg_selftest_static(void){bool ok=CFG_BAND_P1_MAX<CFG_BAND_P2_MAX&&CFG_BAND_P2_MAX<CFG_BAND_P3_MAX&&CFG_BAND_P3_MAX<CFG_BAND_P4_MAX&&CFG_BAND_P4_MAX<CFG_BAND_P5_MAX&&CFG_DUTY_MIN<=CFG_DUTY_CREEP&&CFG_DUTY_CREEP<=CFG_DUTY_APPROACH&&CFG_DUTY_APPROACH<=CFG_DUTY_NORMAL&&CFG_TIMEOUT_HOME_MS>=4u*CFG_TIMEOUT_STEP_MS;line(ok?"SELFTEST STATIC PASS":"SELFTEST STATIC FAIL");return ok;}bool dbg_selftest_motion(void){if(!coupled){dbg_coupled_confirm();return false;}line("SELFTEST MOTION");return controller_request(REQ_HOME,0)==MOVE_OK;}
